### PR TITLE
Zap 82 g UI client options

### PR DESCRIPTION
**Pull request by christophechr**
## Describe your changes
Method ArgumentParser added, returning a clientApi
## Issue ticket number and link
https://uwuclub.atlassian.net/browse/ZAP-82?atlOrigin=eyJpIjoiYWYwNDIzMTdkNGEyNGEzM2JiMDZhNzFlMTFhODc2NzUiLCJwIjoiaiJ9
## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have documented my code
- [ ] Do we need to implement unit tests?

### CODE REVIEW

**Review by Beafowl-Pull — APPROVED** [review]

**Review by Valegox — CHANGES_REQUESTED** [review]
You shouldn't return a new instance of `ClientAPI` from its `argumentParser` method, and you should only use a constructor to instanciate ClientAPI.

I think you should create a `ClientParser` class separated from `ClientAPI`.

**Review by Valegox — CHANGES_REQUESTED** [review]
It's better
Your `argumentParser` method should be within the `ParserData` class, not `ClientApi`.

**Comment by Valegox** [comment]
> It's better Your `argumentParser` method should be within the `ParserData` class, not `ClientApi`.

And you can directly put the content of `argumentParser`within `ParserData`'s constructor

**Review by Valegox — CHANGES_REQUESTED** [review]
Please add:
- documentation
- replace teamName by machineName
- apply variable name norm

**Review by Valegox — APPROVED** [review]

**Pull request merged**
